package View;

import Dao.Dao;
import Model.Autor;
import Controller.Listagem;
import conexao.ConexaoFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Model.Livro;
import java.awt.image.BufferedImage;

public class Principal extends javax.swing.JFrame {
    
    BufferedImage imagemFundo;
    
    public Principal() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        bloquear_botoes();
        preencher_Tabela("Select * from autor");
        preencher_Tabela_Livro("Select * from livro");
        popular_ComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("lp1?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        autor_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Autor_1 a");
        autor_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : autor_1Query.getResultList();
        tela_aut_li = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        camp_nome = new javax.swing.JTextField();
        camp_endereco = new javax.swing.JTextField();
        camp_email = new javax.swing.JTextField();
        btn_salvar_autor = new javax.swing.JButton();
        camp_telefone = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_enviar_livro = new javax.swing.JButton();
        titulo_livro = new javax.swing.JTextField();
        nu_edicao = new javax.swing.JFormattedTextField();
        isbn_id1 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<Object>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_listagem = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Update_list = new javax.swing.JButton();
        btn_cancelar_list = new javax.swing.JButton();
        nome_edit_list = new javax.swing.JTextField();
        endereco_edit_list = new javax.swing.JTextField();
        email_edit_list = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        listagem_id = new javax.swing.JTextField();
        telefone_edit_list = new javax.swing.JFormattedTextField();
        btn_excluir_list = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_tabela_livros = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        camp_edit_list_titulo = new javax.swing.JTextField();
        camp_edit_list_edicao = new javax.swing.JFormattedTextField();
        camp_isbn_list_livro = new javax.swing.JFormattedTextField();
        btn_edit_list_livro = new javax.swing.JButton();
        btn_cancelar_list_livro = new javax.swing.JButton();
        btn_excluir_tab_livro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 32, 46, 18);

        jLabel2.setText("Endereço:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 74, 72, 18);

        jLabel3.setText("Email:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 116, 41, 18);

        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 158, 68, 18);
        jPanel1.add(camp_nome);
        camp_nome.setBounds(102, 29, 343, 30);
        jPanel1.add(camp_endereco);
        camp_endereco.setBounds(102, 71, 343, 24);

        camp_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camp_emailActionPerformed(evt);
            }
        });
        jPanel1.add(camp_email);
        camp_email.setBounds(102, 113, 343, 24);

        btn_salvar_autor.setBackground(new java.awt.Color(41, 132, 21));
        btn_salvar_autor.setForeground(java.awt.Color.white);
        btn_salvar_autor.setText("Salvar");
        btn_salvar_autor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salvar_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_autorActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salvar_autor);
        btn_salvar_autor.setBounds(187, 191, 168, 42);

        try {
            camp_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) 9#### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(camp_telefone);
        camp_telefone.setBounds(102, 155, 343, 24);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lp.gif"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(80, 250, 600, 200);

        tela_aut_li.addTab("Cadastrar_Autor", jPanel1);

        jLabel5.setText("ISBN:");

        jLabel6.setText("Título:");

        jLabel7.setText("N° Edição:");

        btn_enviar_livro.setText("Enviar");
        btn_enviar_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_livroActionPerformed(evt);
            }
        });

        nu_edicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        try {
            isbn_id1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ## - ### - #### - #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        isbn_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbn_id1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Autor:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titulo_livro, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(isbn_id1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nu_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btn_enviar_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isbn_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(titulo_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nu_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_enviar_livro)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        tela_aut_li.addTab("Cadastrar_Livros", jPanel2);

        tabela_listagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela_listagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_listagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_listagem);
        if (tabela_listagem.getColumnModel().getColumnCount() > 0) {
            tabela_listagem.getColumnModel().getColumn(0).setPreferredWidth(200);
            tabela_listagem.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabela_listagem.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabela_listagem.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione um Item da Tebela para Editar"));

        jLabel8.setText("Nome:");

        jLabel9.setText("Endereço");

        jLabel10.setText("Email:");

        jLabel11.setText("Telefone");

        btn_Update_list.setText("Salvar");
        btn_Update_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_listActionPerformed(evt);
            }
        });

        btn_cancelar_list.setText("Cancelar");
        btn_cancelar_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_listActionPerformed(evt);
            }
        });

        nome_edit_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_edit_listActionPerformed(evt);
            }
        });

        jLabel12.setText("ID:");

        try {
            telefone_edit_list.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) 9#### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(endereco_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(email_edit_list, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(telefone_edit_list)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btn_Update_list, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_cancelar_list, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(listagem_id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(listagem_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(nome_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(endereco_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(email_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(telefone_edit_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Update_list)
                    .addComponent(btn_cancelar_list))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_excluir_list.setText("Excluir");
        btn_excluir_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_listActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_excluir_list)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluir_list)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tela_aut_li.addTab("Listar_Autor", jPanel3);

        lista_tabela_livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        lista_tabela_livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_tabela_livrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_tabela_livros);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione um Item na tabela para Editar"));

        jLabel13.setText("ISBN:");

        jLabel14.setText("Tírtulo:");

        jLabel15.setText("N° Edição");

        camp_edit_list_edicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###########0"))));

        try {
            camp_isbn_list_livro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### - ## - ### - #### - #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_edit_list_livro.setText("Salvar");
        btn_edit_list_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_list_livroActionPerformed(evt);
            }
        });

        btn_cancelar_list_livro.setText("Cancelar");
        btn_cancelar_list_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_list_livroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(camp_edit_list_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(camp_isbn_list_livro)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_edit_list_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_cancelar_list_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(camp_edit_list_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(camp_isbn_list_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(camp_edit_list_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(camp_edit_list_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_list_livro)
                    .addComponent(btn_cancelar_list_livro))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btn_excluir_tab_livro.setText("Excluir");
        btn_excluir_tab_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_tab_livroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_excluir_tab_livro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluir_tab_livro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tela_aut_li.addTab("Listar_livros", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela_aut_li)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tela_aut_li))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void bloquear_botoes() {
        listagem_id.setEnabled(false);
        nome_edit_list.setEnabled(false);
        email_edit_list.setEnabled(false);
        telefone_edit_list.setEnabled(false);
        endereco_edit_list.setEnabled(false);
        btn_Update_list.setEnabled(false);
        btn_cancelar_list.setEnabled(false);
        camp_edit_list_edicao.setEnabled(false);

        camp_edit_list_titulo.setEnabled(false);
        camp_isbn_list_livro.setEnabled(false);

    }

    public void limpar_campos() {
        listagem_id.setText("");
        email_edit_list.setText("");
        endereco_edit_list.setText("");
        nome_edit_list.setText("");
        telefone_edit_list.setText("");
        telefone_edit_list.setText("");
        camp_email.setText("");
        camp_endereco.setText("");
        camp_nome.setText("");
        camp_telefone.setText("");
        camp_isbn_list_livro.setText("");
        titulo_livro.setText("");
        nu_edicao.setText("");
        isbn_id1.setText("");
        camp_edit_list_edicao.setText("");
        camp_edit_list_titulo.setText("");

    }

    public void Atualizar_Autor() {
        Dao dao;
        try {
            //System.out.println(""+camp_nome.setText());
            dao = new Dao();
            Autor autor = new Autor();
            if (nome_edit_list.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O Campo Nome deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (endereco_edit_list.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Endereço deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (email_edit_list.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Email deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (telefone_edit_list.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Telefone deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else {

                int id_autor = Integer.parseInt(listagem_id.getText());
                autor.setId(id_autor);

                autor.setNome(nome_edit_list.getText());
                autor.setTelefone(telefone_edit_list.getText());
                autor.setEndereco(endereco_edit_list.getText());
                autor.setEmail(email_edit_list.getText());

                dao.Update(autor);
                preencher_Tabela("select * from autor");

                JOptionPane.showMessageDialog(null, "Atualizado com sussesso!!!");
                limpar_campos();
                bloquear_botoes();

            }

        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void Atualizar_Livro() {
        Dao dao;
        try {
            //System.out.println(""+camp_nome.setText());
            dao = new Dao();
            Livro liv = new Livro();
            if (camp_isbn_list_livro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O Campo ISBN do Livro deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (camp_edit_list_titulo.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Titulo deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (camp_edit_list_edicao.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo N° Edição deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else {

                liv.setIsbn(camp_isbn_list_livro.getText());

                liv.setTitulo(camp_edit_list_titulo.getText());

                int id_liv2 = Integer.parseInt(camp_edit_list_edicao.getText());
                liv.setEdicao(id_liv2);

                dao.Update_livro(liv);
                preencher_Tabela_Livro("select * from livro");

                JOptionPane.showMessageDialog(null, "Atualizado com sussesso!!!");
                limpar_campos();

            }

        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void pegar_dados_tabela() {
        listagem_id.setText(tabela_listagem.getValueAt(tabela_listagem.getSelectedRow(), 0).toString());
        nome_edit_list.setText(tabela_listagem.getValueAt(tabela_listagem.getSelectedRow(), 1).toString());
        endereco_edit_list.setText(tabela_listagem.getValueAt(tabela_listagem.getSelectedRow(), 2).toString());
        email_edit_list.setText(tabela_listagem.getValueAt(tabela_listagem.getSelectedRow(), 3).toString());
        telefone_edit_list.setText(tabela_listagem.getValueAt(tabela_listagem.getSelectedRow(), 4).toString());
    }

    public void ativar_botoes() {
        nome_edit_list.setEnabled(true);
        listagem_id.setEnabled(true);
        email_edit_list.setEnabled(true);
        telefone_edit_list.setEnabled(true);
        endereco_edit_list.setEnabled(true);
        btn_Update_list.setEnabled(true);
        btn_cancelar_list.setEnabled(true);

    }

    public void preencher_Tabela(String sql) throws SQLException, Exception {
        ArrayList dados = new ArrayList();

        Connection minha_conexao = new ConexaoFactory().conexao();

        PreparedStatement ps = minha_conexao.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        String[] Colunas = new String[]{"ID", "Nome", "Endereco", "Email", "Telefone"};
        try {

            while (rs.next()) {

                dados.add(new Object[]{rs.getInt("idAutor"), rs.getString("nome"),
                    rs.getString("endereco"),
                    rs.getString("email"),
                    rs.getString("telefone")});

            }

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro ao preencher Array List da Tabela" + ex);
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Listagem modelo = new Listagem(dados, Colunas);
        tabela_listagem.setModel(modelo);
        tabela_listagem.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabela_listagem.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabela_listagem.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabela_listagem.getColumnModel().getColumn(3).setPreferredWidth(170);
        tabela_listagem.getColumnModel().getColumn(4).setPreferredWidth(150);
        tabela_listagem.getTableHeader().setReorderingAllowed(false);
        tabela_listagem.setAutoResizeMode(tabela_listagem.AUTO_RESIZE_OFF);
        tabela_listagem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencher_Tabela_Livro(String Sql) throws Exception {
        ArrayList dados = new ArrayList();

        Connection minha_conexao = new ConexaoFactory().conexao();

        PreparedStatement ps = minha_conexao.prepareStatement(Sql);
        ResultSet rs = ps.executeQuery();

        String[] Colunas = new String[]{"ISBN", "Título", "N° Edição", "Autor"};
        try {

            while (rs.next()) {

                dados.add(new Object[]{
                    rs.getString("isnb"),
                    rs.getString("titulo"),
                    rs.getInt("n_edicao"),
                    rs.getString("nome_autor"),});

            }

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro ao preencher Array List da Tabela" + ex);
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Listagem modelo = new Listagem(dados, Colunas);
        lista_tabela_livros.setModel(modelo);

    }

    public void popular_ComboBox() throws Exception {
        Dao dao = new Dao();
      
        for (Autor aut : dao.read()) {
            jComboBox1.addItem(aut.getNome());
        }
        jComboBox1.repaint();
    }

    private void camp_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camp_emailActionPerformed
        // TODO create your handling code here:
    }//GEN-LAST:event_camp_emailActionPerformed

    private void nome_edit_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_edit_listActionPerformed

    }//GEN-LAST:event_nome_edit_listActionPerformed

    private void btn_Update_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_listActionPerformed
        // TODO create your handling code here:

        Atualizar_Autor();


    }//GEN-LAST:event_btn_Update_listActionPerformed

    private void btn_salvar_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_autorActionPerformed
        // TODO create your handling code here:

        Dao dao;
        try {
            //System.out.println(""+camp_nome.setText());

            if (camp_nome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "O Campo Nome deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (camp_endereco.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Endereço deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (camp_email.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Email deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (camp_telefone.getText().equals("(   ) 9     -     ")) {

                JOptionPane.showMessageDialog(null, "O campo Telefone deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            }
             
            dao = new Dao();
            Autor autor = new Autor();
            autor.setNome(camp_nome.getText());
            autor.setEndereco(camp_endereco.getText());
            autor.setEmail(camp_email.getText());
            //int tele = Integer.parseInt(camp_telefone.getText());
            autor.setTelefone(camp_telefone.getText());
            dao.create(autor);
            preencher_Tabela("select * from autor");
            jComboBox1.removeAllItems();
            popular_ComboBox();
            limpar_campos();
            
            JOptionPane.showMessageDialog(null, "Cadastrado com sussesso!!!");
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        tela_aut_li.setSelectedIndex(2);

    }//GEN-LAST:event_btn_salvar_autorActionPerformed

    private void tabela_listagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_listagemMouseClicked
        // TODO create your handling code here:
        ativar_botoes();
        pegar_dados_tabela();


    }//GEN-LAST:event_tabela_listagemMouseClicked

    private void btn_cancelar_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_listActionPerformed

        bloquear_botoes();
        limpar_campos();

    }//GEN-LAST:event_btn_cancelar_listActionPerformed

    private void btn_excluir_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_listActionPerformed
        Dao dao;
        Autor aut = new Autor();

        bloquear_botoes();

        try {

            dao = new Dao();
            int id_autor = Integer.parseInt(listagem_id.getText());
            aut.setId(id_autor);
            switch (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este Item", "Aviso", JOptionPane.YES_NO_OPTION)) {
                case 0:
                    dao.Remove(aut);

                    break;

                case 1:
                    JOptionPane.showMessageDialog(null, "Nenhum dado foi excluido", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            limpar_campos();
            preencher_Tabela("select * from autor");
           
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_excluir_listActionPerformed

    private void btn_enviar_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_livroActionPerformed

        try {
             if (isbn_id1.getText().equals("    -    -     -      -  ")) {
                JOptionPane.showMessageDialog(null, "O Campo ISBN deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else if (titulo_livro.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo Título deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (nu_edicao.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "O campo N° Edição deve ser Preenchido!!!", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;

            } 
            Dao dao = new Dao();
            Autor autor = new Autor();

            autor.setNome(jComboBox1.getSelectedItem().toString());
            Livro liv = new Livro();

            liv.setIsbn(isbn_id1.getText());

            liv.setTitulo(titulo_livro.getText());

            int num = Integer.parseInt(nu_edicao.getText());
            liv.setAutor(autor);
            liv.setEdicao(num);
            dao.create_livro(liv);
            JOptionPane.showMessageDialog(null, "Cadastrado com Susseso!!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            limpar_campos();
            camp_edit_list_edicao.setEnabled(false);

            camp_edit_list_titulo.setEnabled(false);
            preencher_Tabela_Livro("select * from livro");
            tela_aut_li.setSelectedIndex(3);
        } catch (Exception e) {
            Logger.getLogger(Dao.class.getName()).log(Level.SEVERE, null, e);
//JOptionPane.showMessageDialog(null, "Não Foi possivel Cadastrar!!!", "Error", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_enviar_livroActionPerformed

    private void lista_tabela_livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_tabela_livrosMouseClicked
        // TODO create your handling code here:
        camp_edit_list_edicao.setEnabled(true);
        camp_isbn_list_livro.setEnabled(true);
        camp_edit_list_titulo.setEnabled(true);
        camp_isbn_list_livro.setText(lista_tabela_livros.getValueAt(lista_tabela_livros.getSelectedRow(), 0).toString());
        camp_edit_list_titulo.setText(lista_tabela_livros.getValueAt(lista_tabela_livros.getSelectedRow(), 1).toString());
        camp_edit_list_edicao.setText(lista_tabela_livros.getValueAt(lista_tabela_livros.getSelectedRow(), 2).toString());
        jComboBox1.setToolTipText(lista_tabela_livros.getValueAt(lista_tabela_livros.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_lista_tabela_livrosMouseClicked

    private void btn_edit_list_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_list_livroActionPerformed
        // TODO create your handling code here:
        try {
            Atualizar_Livro();

            bloquear_botoes();
            limpar_campos();
        } catch (Exception e) {

        }

    }//GEN-LAST:event_btn_edit_list_livroActionPerformed

    private void btn_cancelar_list_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_list_livroActionPerformed

        camp_edit_list_edicao.setEnabled(false);

        camp_edit_list_titulo.setEnabled(false);
        limpar_campos();
        camp_edit_list_edicao.setText("");
        camp_edit_list_titulo.setText("");
    }//GEN-LAST:event_btn_cancelar_list_livroActionPerformed

    private void btn_excluir_tab_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_tab_livroActionPerformed
        Dao dao;
        Livro liv = new Livro();

        bloquear_botoes();

        try {

            dao = new Dao();

            liv.setIsbn(camp_isbn_list_livro.getText());
            switch (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este Item", "Aviso", JOptionPane.YES_NO_OPTION)) {
                case 0:
                    dao.Remove_Livro(liv);

                    break;

                case 1:
                    JOptionPane.showMessageDialog(null, "Nenhum dado foi excluido", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    break;
            }
            limpar_campos();
            camp_edit_list_edicao.setEnabled(false);
            camp_edit_list_titulo.setEnabled(false);
            camp_isbn_list_livro.setEnabled(false);
            preencher_Tabela_Livro("select * from livro");
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO create your handling code here:

    }//GEN-LAST:event_btn_excluir_tab_livroActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

//        try {
//            popular_ComboBox();
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void isbn_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbn_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbn_id1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Controller.Autor_1> autor_1List;
    private javax.persistence.Query autor_1Query;
    private javax.swing.JButton btn_Update_list;
    private javax.swing.JButton btn_cancelar_list;
    private javax.swing.JButton btn_cancelar_list_livro;
    private javax.swing.JButton btn_edit_list_livro;
    private javax.swing.JButton btn_enviar_livro;
    private javax.swing.JButton btn_excluir_list;
    private javax.swing.JButton btn_excluir_tab_livro;
    private javax.swing.JButton btn_salvar_autor;
    private javax.swing.JFormattedTextField camp_edit_list_edicao;
    private javax.swing.JTextField camp_edit_list_titulo;
    private javax.swing.JTextField camp_email;
    private javax.swing.JTextField camp_endereco;
    private javax.swing.JFormattedTextField camp_isbn_list_livro;
    private javax.swing.JTextField camp_nome;
    private javax.swing.JFormattedTextField camp_telefone;
    private javax.swing.JTextField email_edit_list;
    private javax.swing.JTextField endereco_edit_list;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JFormattedTextField isbn_id1;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lista_tabela_livros;
    private javax.swing.JTextField listagem_id;
    private javax.swing.JTextField nome_edit_list;
    private javax.swing.JFormattedTextField nu_edicao;
    private javax.swing.JTable tabela_listagem;
    private javax.swing.JTabbedPane tela_aut_li;
    private javax.swing.JFormattedTextField telefone_edit_list;
    private javax.swing.JTextField titulo_livro;
    // End of variables declaration//GEN-END:variables
}
